name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Docker-compose Build
      run: docker-compose build --no-cache
    - name: Docker-compose Up
      run: docker-compose up --exit-code-from=scopeagent-reference-springboot2 scopeagent-reference-springboot2
      env:
        SCOPE_DSN: ${{ secrets.SCOPE_DSN }}
    - name: Docker-compose Down
      if: always()
      run: docker-compose down -v
      
