name: Scope

on:
  push:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: docker run -d -p 3307:3306 -e MYSQL_ROOT_PASSWORD='' -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=test  mysql --default-authentication-plugin=mysql_native_password
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Scope for Maven
      uses: undefinedlabs/scope-for-maven-action@v1
      with:
        dsn: ${{secrets.SCOPE_DSN}}
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: scopelogs
        path: /home/runner/work/scopeagent-reference-springboot2/scopeagent-reference-springboot2/logs
